apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  jwt-issuer: "finance-tracker-auth"
  redis-host: "redis"
  redis-port: "6379"
  auth-service-url: "http://auth-service"
  transaction-service-url: "http://transaction-service"
  budget-service-url: "http://budget-service"
  notification-service-url: "http://notification-service"
  analytics-service-url: "http://analytics-service"
  cors-origin: "*"
