apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: finance-tracker
  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: serviceaccount
